### ISSUE TITLE
Multiple stations

### ISSUE THREAD

**Issue by powerscooter** [nilstgmd/hvv-card#12]
First of all, I like your card very much. Thanks for your work! :-) 

My question: 
It is possible to show departures from more than one station. 

In my example I have two bus stations near to my apartment. 
Would be nice when I can show the departures from both bus stations in one card.

**Comment by nilstgmd** [comment]
Hi @powerscooter , this is not possible at the moment. For multiple stations I always used multiple dedicated cards put into a Vertical Stack.

How would you prefer to see multiple stations in one card? As a unified list or also separated by station?

**Comment by nilstgmd** [comment]
Fixed with release `0.2.0`
