### ISSUE TITLE
Departures not sorted by time

### ISSUE THREAD

**Issue by C-hiba** [nilstgmd/hvv-card#4]
I really love this custom card. Especially since I never really got in to templating. 

However, I'm having the issue that the departures are not always sorted by departure time. How can I fix that?

![Abfahrtzeiten](https://user-images.githubusercontent.com/20547089/149848010-5c33fc3b-53d7-4aaf-bf1c-1f219c91f6cf.jpg)

**Comment by C-hiba** [comment]
Ok... I believe the order is correct. The issue seems to be, that the hours are not displayd.

**Comment by BastianKamp** [comment]
Ah that makes sense. 
I have a station where every hour just one bus comes. And the widget shows multiple times the same info.
Already thought that it would repeat the departures if there are no.
